TUNING.SENDI = {
	INTERNAL_TYPE_ZERO = 0, -- ??? lol

	DEFAULT_HEALTH = 130,
	DEFAULT_HUNGER = 160,
	DEFAULT_SANITY = 90,

	MANA_MAX_DEFAULT = 100,		-- 마나 최대치 기본값
	MANA_CURRENT_DEFAULT = 50,	-- 마나 수치 기본값
	MANA_CURRENT_ONRESPAWN = 0, -- 부활했을 때 마나 수치

	SKILL_RAPIER_DAMAGE_1 = 20, -- 돌진할 때 데미지
	SKILL_RAPIER_DAMAGE_2 = 55, -- 터질 때 데미지
	SKILL_RAPIER_HUNGERCOST = 15, -- 이그니아 런 배고픔 코스트

	SKILL_IGNIARUN_HUNGERCOST = 2, -- 이그니아 점프 배고픔 코스트

	ARMOR1_CONDITION = 2000, -- 센디 아머1 내구도 
	ARMOR1_EFFICIENCY = 0.55, -- 방어율
}